### ISSUE TITLE
Togliere i tastini di scarica il rapporto e le sintesi anche delle diverse sezioni.

### ISSUE THREAD

**Issue by ebergam** [ondata/sbilanciamoci-manovra2017#1]
Lasciare solo la sintesi principale in home.

**Comment by giuragu** [comment]
Ottimo. Prendo in carico la issue @ebergam :)

**Comment by giuragu** [comment]
@ebergam ho provveduto utilizzando i tag "commento" affinché il codice rimanga così da farlo riemergere facilmente quando sarà opportuno. Che ne pensi?
