### ISSUE TITLE
Creare somma di entrate e uscite per ogni categoria

### ISSUE THREAD

**Issue by ebergam** [ondata/sbilanciamoci-manovra2017#2]

**Comment by giuragu** [comment]
suggeriscono effetti grafici (es. frecce) da associare ai valori totali di entrata e uscita

**Comment by giuragu** [comment]
Da valutare la possibilità di mostrare per ogni categoria lo specifico screenshot provieniente dall'infografica. Ne è stato inserito un esempio per la pagina fisco e finanza.
Sempre nella stessa pagina inserito, sempre a titolo di esempio, somma entrate e uscite con immagini-freccia

**Comment by giuragu** [comment]
Riportare solo frecce: Ridurne dimensione e riportate il testo all'interno

**Comment by giuragu** [comment]
Fatto per ogni categoria, una volta che ci saranno le cifre ufficiali basterà creare le diverse "arrows" in cartella img/arrows come già fatto per fisco_finanza. Rinominare in relazione al nome pagina

**Comment by giuragu** [comment]
Matteo si occuperà della creazione e dell'inserimento nelle diverse sezioni

**Comment by botiq** [comment]
Ho mandato un'email poco fa con le frecce di fisco e finanza. Le potete visualizzare anche qui [http://controfinanziaria.sbilanciamoci.org/img/frecciaverde.png](http://controfinanziaria.sbilanciamoci.org/img/frecciaverde.png) 
Invece di due immagini ( per.es fisco_finanza_green.png & fisco_finanza_red.png) per categoria, io sarei per inserirne una sola, tipo fisco_finanza_frecce.png.
Come font ho utilizzato Open Sans Extra Bold. Fatemi sapere se secondo voi va bene o è meglio cambiarlo.

**Comment by giuragu** [comment]
@botiq Assolutamente si. Per me vanno benissimo e va benissimo anche come unica immagine.

**Comment by botiq** [comment]
@giuragu le frecce non si ridimensionano cambiando la dimensione dello schermo, e su mobile si vedono male. Dovresti aggiungere nei css
.col-md-12.column.text-center img {
    width: 100%;
}
Oppure aggiungi un classe div specifica per il contenitore dove stanno le immagini.

**Comment by giuragu** [comment]
@botiq ho visto che sei intervenuto. Grazie Matteo.
