### ISSUE TITLE
Modificare per il 2017 la tabella origine dei dati.

### ISSUE THREAD

**Issue by ebergam** [ondata/sbilanciamoci-manovra2017#3]
Modificare per il 2017 la tabella origine dei dati.

**Comment by giuragu** [comment]
Fatto per tutte le pagine che contengono tabelle dati. 

Rimane da correggere il focus "Lavoro e reddito" che passando a "Politiche industriali, lavoro e reddito" richiede probabilmente la variazione delle key word che determinano la visualizzazione dei dati limitata a tale categoria

**Comment by giuragu** [comment]
La variazione della key word non era probabilmente necessaria. Adesso anche la sezione "Lavoro e reddito" è ok
