### ISSUE TITLE
Creare archivio 2016 e relativo link su Home e accorgimenti

### ISSUE THREAD

**Issue by giuragu** [ondata/sbilanciamoci-manovra2017#4]
- [x]  Già disponibile la cartella [archivio](https://github.com/ondata/sbilanciamoci-manovra2017/tree/master/archivio_controfinanziaria2016);
- [x] Su di essa va puntato un link (menu, banner, ecc...);
- [x] In ogni pagina garantire un'identificazione e distinzione chiara all'utente tra i contenuti della versione 2016 e della 2017 (variabili: loghi, colori, testi, altro)

**Comment by ebergam** [comment]
@giuragu su questo ragioniamo perché, ora che ci penso, ogni singolo href nel sito vecchio se lasciato così punterà sulle risorse 2017. Esempio se href punta a ./images/immagine.jpg andrà a pescare dentro alla cartella 2017 a meno che non cambiamo tutti gli href con /archivio_2016/images/immagine.jpg.
Forse è meglio pensare a qualcosa di più furbo

**Comment by giuragu** [comment]
@ebergam siccome tutte il sito 2016 si trova nel nuovo reposotory alla sottocartella  "archivio_controfinanziaria2016" tutti gli href contenuti nelle pagine 2016 ivi contenute (es. index.html, analisi e dati.html, ecc...) rimanendo come sono (es.: /images/immagine.jpg) dovrebbero cercare i contenuti sempre nella sottocartella archivio_controfinanziaria2016 e non andare alla superiore e cioè sbilanciamoci-manovra2017. Ho verificato e sembra che sia tutto ok. Ma...puoi verificare pure tu? Non vorrei prendere una cantonata

**Comment by giuragu** [comment]
@ebergam trovo ottima l'idea del cookie

**Comment by ebergam** [comment]
@giuragu dici? è molto comoda e veloce, però non so, sparisce subito. E se ritorni sul sito non lo rivedi più.. Forse è meglio un normale banner statico! Intanto comunque abbiamo questo come punto di partenza, poi ci ragioniamo :)

**Comment by giuragu** [comment]
@ebergam in effetti se scompare non andrebbe....si punterei allo statico

**Comment by ebergam** [comment]
@giuragu che dici così?

**Comment by giuragu** [comment]
@ebergam lo trovo ottimo! inserito in ogni pagina facendolo scorrere insieme al menu principale così da averlo sempre sott'occhio, procedendo in verticale sulla pagina, sarebbe perfetto...che ne pensi?

**Comment by giuragu** [comment]
Inserito link ad archivio su Home

**Comment by giuragu** [comment]
Ci sarebbe da modificare il colore della barra di navigazione da "giallo" a "verde" e correggere il testo in "Vai al Rapporto Sbilanciamoci! 2017"

**Comment by giuragu** [comment]
@ebergam potresti qui chiudere tu riportando su tutte le pagine dell'archivio 2016 il banner statico che hai ideato, modificando colore, e facendo in modo che rimanga visibile nonostante la pagina scorra verso il basso?

**Comment by ebergam** [comment]
@giuragu Ho committato i nuovi files con i banner verdi statici, dimmi se ti garba

**Comment by giuragu** [comment]
Ottimo. Modifica in master. Da riprortare in gh-pages
