### ISSUE TITLE
Aggiornare i contenuti della proposta (testi ed eventuali immagini)

### ISSUE THREAD

**Issue by giuragu** [ondata/sbilanciamoci-manovra2017#6]
- [x] HOME
- [x] Rapporto 2017 
- [x] FISCO E FINANZA
- [ ] POLITICHE INDUSTRIALI, LAVORO E REDDITO
- [x] CULTURA E CONOSCENZA
- [x] AMBIENTE E SVILUPPO SOSTENIBILE
- [x] WELFARE E DIRITTI
- [x] COOPERAZIONE, PACE E DISARMO
- [x] ALTRAECONOMIA
- [x] TUTTE (inserire anche tavola pdf o jpeg)
- [x] INFOGRAFICA
- [x] ANALISI E DATI

**Comment by giuragu** [comment]
Home: 
- [x] Confermare il contributo 8x1000 chiesa valdese. Indicare 2017 anzichè 2016;
- [x] Modificare tutti i riferimenti 2016 in tutte le pagine (attenzione ad archivio);
- [x] Inserire meta immagine in images/sbilanciamoci_rapporto_2017.jpg
- [x] I simboli non sono centrati;
- [x] Da "Archivio: Rapporto..." a "Guarda il Rapporto"
- [x] Pulsante "Lavoro e Reddito" diventa "Politiche industriali, lavoro e reddito" (modificare anche link)
- [x] Nascondere sezione Analisi dei dati
- [x] scarica il rapporto 2017 con il testo da definire

**Comment by giuragu** [comment]
@ebergam come procedi tu quando ti trovi a dover modificare le medesime righe html in diverse pagine? Come la seguente per cui dovremmo modificare i riferimenti al 2016 in 2017?
![html_meta](https://cloud.githubusercontent.com/assets/12112056/20106456/891a275e-a5d5-11e6-8306-210523d37536.png)

**Comment by ebergam** [comment]
Mah.. non so se ci sia un metodo furbo e svelto per farlo (citofoniamo @aborruso ).. Così a sentimento mi verrebbe da dire: apro la pagina, 'trova e sostituisci', cerco '6', butto un'occhiata veloce e se è da cambiare faccio un replace, tanto il resto delle stringhe sono uguali no?

**Comment by aborruso** [comment]
@giuragu @ebergam vi sento forte e chiaro: farei un trova e sostituisci multifile. Si può fare con tutti gli editor di testo seri (a me piacciono Notepad++, SublimeText, Atom), e i può fare da riga di comando (con sed, awk, ecc.).

In notepad++:
1. lavorate su più file;
2. impostando su quale cartella;
3. impostando eventualmente su quali formati;
4. utilizzando eventualmente le espressioni regolari.

![image](https://cloud.githubusercontent.com/assets/30607/20112070/2310b700-a5eb-11e6-9262-f0313dde3eac.png)

Così in SublimeText:

![image](https://cloud.githubusercontent.com/assets/30607/20112169/8de89034-a5eb-11e6-8654-5502c7540dfd.png)

**Comment by giuragu** [comment]
@aborruso @ebergam grazieeee l'ho appena fatto utilizzando Atom!

**Comment by nelsonmau** [comment]
minchia lo sapevo che @aborruso usa notepad++, mai fidarsi dei matusa!

**Comment by giuragu** [comment]
@ebergam Inserire meta immagine in images/sbilanciamoci_rapporto_2017.jpg me ne occupo io.
Per quanto riguarda "I simboli non sono centrati" potresti occupartene tu?
