### ISSUE TITLE
Modificare il carattere dei testi

### ISSUE THREAD

**Issue by giuragu** [ondata/sbilanciamoci-manovra2017#8]

**Comment by giuragu** [comment]
@ebergam ne parlavi durante la call su come volevi proceder. Ecco...come volevi procedere :)

**Comment by ebergam** [comment]
scegli quello che più ti aggrada :) https://fonts.google.com/

**Comment by giuragu** [comment]
@ebergam proponevano un Sans...direi un Open Sans...

**Comment by ebergam** [comment]
done :)
